### ISSUE TITLE
where do i put all my bot token and prefix :0

### ISSUE THREAD

**Issue by dog1cool1** [REVENGE977/Server-Captcha#1]

**Comment by REVENGE977** [comment]
https://github.com/REVENGE977/Server-Captcha/blob/04fdcd394ae1fb71d644635fb51d4f44bd6f3cc6/server.js#L4
https://github.com/REVENGE977/Server-Captcha/blob/04fdcd394ae1fb71d644635fb51d4f44bd6f3cc6/server.js#L138
